FROM python:3.8.3-buster

COPY /src/server/ /pearish/
COPY requirements.txt ./

RUN pip install -r requirements.txt
RUN python -m nltk.downloader punkt
WORKDIR /pearish

# CMD ["python3", "app.py"]
# CMD gunicorn -w 4 --bind 0.0.0.0:$PORT wsgi
CMD ["gunicorn"  , "-b", "0.0.0.0:8000", "--workers", "2", "--threads", "4", "app:app"]