FROM python:3.8.3-buster

COPY /src/server/ /pearish/
COPY requirements.txt ./

RUN pip install -r requirements.txt
RUN python -m nltk.downloader punkt
WORKDIR /pearish

CMD ["python3", "app.py"]